language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: mYF3KWLQe6dsOR++P5FpeDI4wNu/I2nyq566I/Yey/8PBC7rj28v6yczsh9d/1pZK8zd1r4i/YI/Zs4BXF2XCGzlWhwT/bcIHirJ3/3xj19V80kpM019lS7hCEVGqJjLtuSY+557LhaZCpI5LZYTn2GWEZK7rtN0U9QE+FMGFeYHikffvWonrp+Oa8vk7Sb6bCYjUSyqO/jvBZmeedMfrOSJqEhoKvkIpIZ7oGUX8LY1BvDrI8l6dr2zmeSho/1r/Rz3C7F3JJxgdkv0+FnIdznRX0poMx/kqapfPaGWl9iVgQQ7+d74ngyH7qEiE/LA3UH0iolhURja8SDlKmkLDwSdU1ZyfFRoCHd64GA+aA4xuuyClToZSyV3zeYGr1iOhf+CLzNNutsXQ11PVvGk/S7qPDcBUAvv1JdeS2Eys6xcmxFMNZAkk/MOuQoeTtqGNTJsoolYF7qeDViso6rJHH9bmnkW6DTFxxiQoRnnSF2ojPPOFDvt1GnZ9Qzakd1oWr8LWQBGC5cvnrAJYHntqZnF+41Ef3hHFw8VXSezEHvYqxbw3SMRIOZjBu21apeS81J04lL1RzpunKfEtuwLyAXcFpwUVWoWC63oCn2YNM/yhxERJtTQPOmu6DdaiqLf6VJdhLBBZ8QMyjA683SrIYww1MasJXIIE0Bvu10Ovgk=
  on:
    tags: true
    repo: xogroup/joi2gql
  notifications:
    slack:
      secure: TBDxUfHiPNvuzFqFNWfqU4k2uVvhM5GtJzzQNpeezuOY5w3IJzcofA9a9wK/swXejzgtBbqXgwbt2AZJS/YJpsvcJsZa/VaVMUExx1dzHo/m26fTOHpBcV2vOHK2ThkUAIYwA3sdKhJa7h8rn2cKV18ttKBStb+4kJ3FoIus8miAihdiikOGKTdMFx+GPSksi7XtEpPNRyFZTPmTWhuidWSyhLFNKr7hUBJqzlEpJ/fZNXr+mboVOTlWcDyQ+Sul/fdiLiqsABVuA2t7Mn2Tp3JtVwZBUHPk6m4blviW2xYdRjTU4b7dxoRMXvXkYzTofcxY3j9VuP+N/ceqM0I0zx4lFrArZA8k+d0hXQmcrDU5kIPOznY/gtWkXeVElcpFPA9W2JkQw1icbHKpKly09Q4cWGmrEjXx/fwFA5cW4DXRFo71T3crlYBLtFFTCmKT+4ckUugUXL2MYZAuwbk8VqwTKGMNeL1FwhQxu9G/RtCXO5aH3HmQm51vS734f5O0Wukp+wvo4G9H1L7GbHLUs9gi0qVxOE4Wd3ploSUkevj6R58U34Qxft6u6+MyvcEYwQRX1/CvbtanIFWFynwXEJFCcFNqXMBeiV+jJG93qdHwz0TcJuIiNl7KXDvKsXZEOPIdV46YQ9GLtF8J3Pr2fFhfJ0f2ffYROLnFS+eL8Dg=
